### ISSUE TITLE
Email Address

### ISSUE THREAD

**Issue by 1995parham** [ovflowd/ovflowd-old.github.io#2]
I had visited your homepage and I couldn't find your email address so I opened this issue and I am sorry to bother you. I think email address is one of a good way of communication for people like me that do not have social media like twitter or telegram. I will be glad if I can have your email address.

**Comment by ovflowd** [comment]
Sure thing, you're not bothering me 😅😉

I don't put my emails publicly because of my privacy.

My email is cwunder@gnome.org

Cheers
